on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Hello world action step
        id: hello
        uses: marcocastellani/xml-poke@v5
        with:
          file-glob: 'pippo.xml'
          select: '/android:manifest/@android:versionCode'
          set: '666'
          namespace: 'http://schemas.android.com/apk/res/android'
          namespace-alias: android
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.result }}"
